"use client";
import Link from "next/link";
import { GitBranch, Megaphone, MessageSquare, Search, Users, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CampaignStatusBadge } from "@/components/campaigns/CampaignBadges";
import type { CampaignSummary } from "@/lib/types/campaigns";
const GOLD="#C9A84C", TEXT="#F0ECE4", MUTED="#858592", PANEL="#101016";
function fmt(value:string|null){if(!value)return "No activity yet";return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}
export default function CampaignsClient(){
 const [items,setItems]=useState<CampaignSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[type,setType]=useState("All");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/airtable/campaigns",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.campaigns);}catch(e){setError(e instanceof Error?e.message:"Could not load campaigns");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>items.filter(c=>(status==="All"||c.status===status)&&(type==="All"||c.type===type)&&`${c.name} ${c.description}`.toLowerCase().includes(query.toLowerCase())),[items,query,status,type]);
 const totalLeads=items.reduce((n,c)=>n+c.totalLeads,0),messages=items.reduce((n,c)=>n+c.messagesSent,0);
 const summaryCards=[{label:"Total Campaigns",value:items.length,icon:<Megaphone size={18} color={GOLD}/>},{label:"Active Campaigns",value:items.filter(c=>c.status==="Active").length,icon:<Zap size={18} color={GOLD}/>},{label:"Total Campaign Leads",value:totalLeads,icon:<Users size={18} color={GOLD}/>},{label:"Messages Sent",value:messages,icon:<MessageSquare size={18} color={GOLD}/>}];
 return <div className="space-y-6">
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summaryCards.map(card=><div key={card.label} className="rounded-xl border p-4" style={{background:PANEL,borderColor:"rgba(201,168,76,.14)"}}>{card.icon}<p className="mt-3 text-2xl font-bold" style={{color:TEXT}}>{card.value}</p><p className="text-xs" style={{color:MUTED}}>{card.label}</p></div>)}</div>
 <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3" size={16} color={MUTED}/><input aria-label="Search campaigns" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campaigns" className="w-full rounded-lg border bg-transparent py-2.5 pl-10 pr-3 text-sm text-white" style={{borderColor:"#292932"}}/></label>{[[status,setStatus,["All","Active","Paused","Coming Soon"]],[type,setType,["All","Automatic","Manual Enrollment"]]].map(([value,setter,options],i)=><select aria-label={i?"Campaign type":"Campaign status"} key={i} value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="rounded-lg border bg-[#101016] px-3 text-sm text-white" style={{borderColor:"#292932"}}>{(options as string[]).map(o=><option key={o}>{o}</option>)}</select>)}</div>
 {loading?<div className="grid gap-4 md:grid-cols-2">{[1,2].map(i=><div key={i} className="h-72 animate-pulse rounded-2xl bg-white/5"/>)}</div>:error?<div className="rounded-xl border border-red-500/30 bg-red-500/5 p-6 text-center text-red-300"><p>{error}</p><button onClick={load} className="mt-3 rounded-lg border px-4 py-2">Retry</button></div>:visible.length===0?<div className="rounded-xl border border-white/10 p-10 text-center" style={{color:MUTED}}>No campaigns match these filters.</div>:<div className="grid gap-4 md:grid-cols-2">{visible.map(c=><article key={c.slug} className="rounded-2xl border p-5" style={{background:PANEL,borderColor:`${c.accent}33`}}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl p-3" style={{background:`${c.accent}18`,color:c.accent}}>{c.slug==="speed-to-lead"?<Zap/>:<GitBranch/>}</div><div><h2 className="text-lg font-bold" style={{color:TEXT}}>{c.name}</h2><p className="mt-1 text-sm" style={{color:MUTED}}>{c.description}</p></div></div><CampaignStatusBadge status={c.status}/></div><div className="mt-4 flex flex-wrap gap-2 text-[11px]" style={{color:MUTED}}><span className="rounded-full bg-white/5 px-2 py-1">{c.type}</span>{c.channels.map(ch=><span key={ch} className="rounded-full bg-white/5 px-2 py-1">{ch}</span>)}</div><div className="mt-5 grid grid-cols-4 gap-2 text-center">{[["Leads",c.totalLeads],["Active",c.activeLeads],["Completed",c.completedLeads],["Messages",c.messagesSent]].map(([l,v])=><div key={String(l)}><p className="font-bold" style={{color:TEXT}}>{v}</p><p className="text-[10px]" style={{color:MUTED}}>{l}</p></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4"><p className="text-xs" style={{color:MUTED}}>Last activity: {fmt(c.lastActivity)}</p><Link href={`/campaigns/${c.slug}`} className="rounded-lg px-4 py-2 text-xs font-bold" style={{background:c.accent,color:"#08080C"}}>Open Campaign</Link></div></article>)}</div>}</div>;
}
