"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { HeartHandshake, ArrowUpRight } from "lucide-react";
import { DEFAULT_CAMPAIGN, type ReactivationMetrics } from "@/lib/reactivation/model";
export default function ReactivationCampaignCard({query,status,type,onMetrics}:{query:string;status:string;type:string;onMetrics:(data:ReactivationMetrics)=>void}) {
  const [data,setData]=useState<ReactivationMetrics|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/reactivation/metrics",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);onMetrics(body);}catch(e){setError(e instanceof Error?e.message:"Could not load reactivation metrics.");}finally{setLoading(false);}},[onMetrics]);
  useEffect(()=>{void load();},[load]);
  if(!DEFAULT_CAMPAIGN.toLowerCase().includes(query.toLowerCase())||(type!=="All"&&type!=="Manual Enrollment")||(status!=="All"&&status!=="Active"))return null;
  return <article className="rounded-2xl border p-4 sm:p-5" style={{background:"var(--surface-1)",borderColor:"var(--border-subtle)",color:"var(--text-primary)"}}>
    <Link href="/dashboard/dormant-patients" className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-xl" style={{background:"var(--brand-primary-soft)",color:"var(--brand-primary)"}}><HeartHandshake size={20}/></div><div><h2 className="text-base font-bold sm:text-lg">{DEFAULT_CAMPAIGN}</h2><p className="mt-1 text-sm leading-5" style={{color:"var(--text-muted)"}}>Invite dormant patients back through a consent-aware SMS and email sequence.</p></div></div><ArrowUpRight className="shrink-0" size={18}/></Link>
    <div className="mt-4 flex flex-wrap gap-2 text-[11px]" style={{color:"var(--text-muted)"}}>{["Manual Enrollment","SMS","Email","Patient reactivation"].map(v=><span key={v} className="rounded-full px-2 py-1" style={{background:"var(--background-subtle)"}}>{v}</span>)}</div>
    {loading?<div className="py-12 text-sm" role="status">Loading reactivation performance…</div>:error?<div className="py-5 text-sm" role="alert"><p>{error}</p><button onClick={load} className="mt-3 rounded-lg border px-4 py-2">Retry</button></div>:data&&<><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Enrolled",data.total],["Active",data.active],["Completed",data.completed],["Stopped",data.stopped],["SMS sent",data.sms],["Email sent",data.email],["Replies",data.replies],["Bookings",data.bookings]].map(([label,value])=><div key={label} className="rounded-xl px-3 py-2.5" style={{background:"var(--background-subtle)"}}><p className="font-bold">{value}</p><p className="text-[10px]" style={{color:"var(--text-muted)"}}>{label}</p></div>)}</div><div className="mt-4 border-t pt-3 text-xs space-y-2" style={{borderColor:"var(--border-subtle)",color:"var(--text-muted)"}}><p>Delivery failures / not sent or delivered: <strong>{data.failures}</strong></p><p>Stop reasons: {Object.entries(data.stopReasons).map(([reason,count])=>reason+" ("+count+")").join(" · ")||"None recorded"}</p>{data.total===0&&<p>No patients enrolled yet. Open the patient directory to review your first group.</p>}</div></>}
    <Link href="/dashboard/dormant-patients" className="mt-5 inline-flex gap-2 items-center text-xs font-bold" style={{color:"var(--brand-primary)"}}>Open dormant patients <ArrowUpRight size={14}/></Link>
  </article>;
}
