"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, RefreshCw, UserPlus, HeartHandshake, Mail, MessageSquare, Search } from "lucide-react";
import { formatCampaignDate } from "@/lib/campaigns/campaign-date";
import type { ReactivationCampaignData } from "@/lib/reactivation/campaign";
import type { Enrollment, PatientMessage } from "@/lib/reactivation/model";
import PatientDialog from "./PatientDialog";
import DeletePatientButton from "./DeletePatientButton";
import s from "./reactivation.module.css";
const date=(value:string)=>formatCampaignDate(value||null,"Not recorded");
const SIZE=25;
export default function ReactivationCampaign({initial,initialError,canManage,canDelete}:{initial:ReactivationCampaignData|null;initialError:string;canManage:boolean;canDelete:boolean}){
  const [data,setData]=useState(initial),[error,setError]=useState(initialError),[loading,setLoading]=useState(false);
  const [tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[channel,setChannel]=useState("All"),[page,setPage]=useState(1);
  const [target,setTarget]=useState<Enrollment|null>(null),[message,setMessage]=useState<PatientMessage|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(""),[notice,setNotice]=useState("");
  async function refresh(){
    setLoading(true);setError("");
    try{const r=await fetch("/api/reactivation/campaign",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);}
    catch(e){setError(e instanceof Error?e.message:"Could not refresh campaign.");}finally{setLoading(false);}
  }
  async function remove(){
    if(!target||busy)return;setBusy(true);setActionError("");
    try{const r=await fetch("/api/reactivation/stop",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enrollmentId:target.id})});const b=await r.json();if(!r.ok)throw new Error(b.error);setTarget(null);setNotice("Removed from campaign. Scheduled sends cleared; history retained.");await refresh();}
    catch(e){setActionError(e instanceof Error?e.message:"Could not remove enrollment.");}finally{setBusy(false);}
  }
  if(!data)return <div className={s.empty}><HeartHandshake size={28}/><h3>Reactivation campaign unavailable</h3><p role="alert">{error}</p><button className={s.button} disabled={loading} onClick={refresh}>{loading?"Loading…":"Retry"}</button></div>;
  const patients=new Map(data.patients.map(p=>[p.id,p]));
  const name=(ids:string[])=>ids.map(id=>patients.get(id)?.name||"Patient unavailable").join(", ")||"Patient deleted";
  const needle=query.trim().toLowerCase();
  const enrollments=data.enrollments.filter(e=>(status==="All"||e.status===status)&&[name(e.patientIds),e.currentStep,...e.patientIds.flatMap(id=>[patients.get(id)?.phone||"",patients.get(id)?.email||""])].join(" ").toLowerCase().includes(needle));
  const logs=data.messages.filter(m=>(status==="All"||m.status===status)&&(channel==="All"||m.channel===channel)&&[name(m.patientIds),m.step,m.body].join(" ").toLowerCase().includes(needle));
  const rows=tab==="messages"?logs:enrollments;
  const pages=Math.max(1,Math.ceil(rows.length/SIZE)),current=Math.min(page,pages);
  const m=data.metrics;
  const steps=["Step 1 SMS","Step 2 Email","Step 3 SMS"];
  function changeTab(next:string){setTab(next);setQuery("");setStatus("All");setChannel("All");setPage(1);}
  const cardStatus=m.active?"Active":data.paused?"Paused":"Idle";
  return <div className={s.workspace}>
    <div className={s.campaignTop}><Link href="/campaigns" className={s.backLink}><ArrowLeft size={15}/>All campaigns</Link><div className="flex flex-wrap gap-2"><button className={s.button} disabled={loading} onClick={refresh}><RefreshCw size={14}/>{loading?"Refreshing…":"Refresh"}</button>{canManage&&<Link className={s.button+" "+s.primary} href="/dashboard/dormant-patients"><UserPlus size={15}/>Enroll patients</Link>}</div></div>
    <header className={s.campaignHero}><span className={s.avatar}><HeartHandshake size={23}/></span><div><span className={s.eyebrow}>Patient retention · Manual enrollment</span><h2>{data.campaign}</h2><p className={s.muted}>Bring patients back with a three-step SMS and email follow-up. Review who is enrolled, what is scheduled, and what was delivered.</p><p className={s.muted}>Last activity: {date(data.lastActivity)} · Updated {date(data.generatedAt)}</p></div><span className={s.badge+" "+(cardStatus==="Active"?"":s.neutral)}>{cardStatus}</span></header>
    {error&&<p className={s.notice+" "+s.warning} role="alert">{error} Showing the last loaded data.</p>}
    {notice&&<div className={s.notice} role="status">{notice}<button className="ml-4 underline" onClick={()=>setNotice("")}>Dismiss</button></div>}
    <div className={s.kpis}>{[["Enrolled",m.total,"Enrollment records"],["Active",m.active,data.paused+" paused"],["Messages sent",m.sms+m.email,m.sms+" SMS · "+m.email+" email"],["Booked patients",m.bookings,m.replies+" patients replied"]].map(([label,value,detail])=><article key={label} className={s.kpi}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
    <nav className={s.tabs} aria-label="Campaign sections">{[["overview","Overview"],["enrollments","Enrollments · "+data.enrollments.length],["messages","Message log · "+data.messages.length]].map(([key,label])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>changeTab(key)}>{label}</button>)}</nav>
    {tab==="overview"?<>
      <div className={s.campaignGrid}><section className={s.panel}><div className={s.toolbar}><div><h3>Follow-up sequence</h3><p className={s.muted}>Current positions, based on active enrollments.</p></div></div><div className={s.sequence}>{steps.map((step,i)=>{const count=data.enrollments.filter(e=>e.status==="Active"&&e.currentStep===step).length;return <article key={step}><span className={s.avatar}>{i===1?<Mail size={17}/>:<MessageSquare size={17}/>}</span><div><small>STEP {i+1}</small><h4>{step}</h4><p>{count} active {count===1?"patient":"patients"}</p></div></article>;})}</div><p className={s.footer}>Send timing and message content are controlled by the connected automation. This page reports saved schedules; it does not run the sender.</p></section>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Enrollment outcomes</h3><p className={s.muted}>All-time enrollment status</p></div></div><div className={s.breakdown}>{[["Active",m.active],["Paused",data.paused],["Completed",m.completed],["Stopped",m.stopped]].map(([label,count])=><div key={label}><span>{label}</span><span className={s.progress}><i style={{width:(m.total?Number(count)/m.total*100:0)+"%"}}/></span><strong>{count}</strong></div>)}</div>{!m.total&&<p className={s.footer}>No enrollments yet. Add patients from the directory to begin.</p>}</section></div>
      <div className={s.campaignGrid}><section className={s.panel}><div className={s.toolbar}><div><h3>Upcoming sends</h3><p className={s.muted}>Earliest saved schedules · clinic timezone</p></div></div><div className={s.miniList}>{data.enrollments.filter(e=>e.status==="Active"&&e.nextSendAt).sort((a,b)=>Date.parse(a.nextSendAt)-Date.parse(b.nextSendAt)).slice(0,5).map(e=><div key={e.id}><strong>{name(e.patientIds)}</strong><span>{e.currentStep}</span><small>{date(e.nextSendAt)}</small></div>)}{!data.enrollments.some(e=>e.status==="Active"&&e.nextSendAt)&&<p className={s.muted}>No scheduled sends.</p>}</div></section>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Delivery & stop reasons</h3><p className={s.muted}>Recorded outcomes, not estimated performance</p></div></div><div className={s.miniList}><div><strong>{m.failures} not confirmed sent/delivered</strong><small>Includes pending, rejected and other delivery statuses. See the message log for the exact status.</small></div>{Object.entries(m.stopReasons).map(([reason,count])=><div key={reason}><span>{reason}</span><strong>{count}</strong></div>)}{!Object.keys(m.stopReasons).length&&<p className={s.muted}>No stop reasons recorded.</p>}</div></section></div>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Recent messages</h3><p className={s.muted}>Latest delivery records linked to this campaign</p></div><button className={s.button} onClick={()=>changeTab("messages")}>View message log</button></div><div className={s.miniList}>{data.messages.slice(0,4).map(msg=><button key={msg.id} onClick={()=>setMessage(msg)}><strong>{name(msg.patientIds)}</strong><span>{msg.channel} · {msg.status}</span><small>{date(msg.sentAt)}</small></button>)}{!data.messages.length&&<p className={s.muted}>No messages logged yet. Recorded SMS and email deliveries will appear here.</p>}</div></section>
    </>:<section className={s.panel}><div className={s.toolbar}><div><h3>{tab==="messages"?"Message log":"Patient enrollments"}</h3><p className={s.muted}>{rows.length} matching records · newest first</p></div></div>
      <div className={s.filters}><label className={s.search}><Search size={16}/><input aria-label="Search campaign records" className={s.input} placeholder={tab==="messages"?"Search patient, step or message…":"Search patient, contact or step…"} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label className={s.label}>Status<select className={s.input} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{["All",...new Set((tab==="messages"?data.messages:data.enrollments).map(r=>r.status))].map(v=><option key={v}>{v}</option>)}</select></label>{tab==="messages"&&<label className={s.label}>Channel<select className={s.input} value={channel} onChange={e=>{setChannel(e.target.value);setPage(1);}}>{["All",...new Set(data.messages.map(m=>m.channel))].map(v=><option key={v}>{v}</option>)}</select></label>}</div>
      {!rows.length?<div className={s.empty}><Search size={24}/><h3>No {tab==="messages"?"messages":"enrollments"} match</h3><p className={s.muted}>Try another search or filter. No records are fabricated when activity is empty.</p></div>:<div className={s.tableWrap}><table className={s.table}><thead><tr>{(tab==="messages"?["Patient","Channel / step","Sent at","Delivery status","Message"]:["Patient","Status","Current step","Enrolled","Next send","Last sent","Stop reason","Actions"]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>
      {tab==="messages"?logs.slice((current-1)*SIZE,current*SIZE).map(msg=><tr key={msg.id}><td>{name(msg.patientIds)}</td><td>{msg.channel}<br/><small>{msg.step||"Not recorded"}</small></td><td>{date(msg.sentAt)}</td><td><span className={s.badge+" "+s.neutral}>{msg.status}</span></td><td><button className={s.messagePreview} onClick={()=>setMessage(msg)}>{msg.body||"View message details"}</button></td></tr>):enrollments.slice((current-1)*SIZE,current*SIZE).map(e=><tr key={e.id}><td><strong>{name(e.patientIds)}</strong><br/><small>{e.patientIds.map(id=>patients.get(id)?.email||patients.get(id)?.phone).filter(Boolean).join(", ")}</small></td><td><span className={s.badge+" "+(e.status==="Active"?"":s.neutral)}>{e.status}</span></td><td>{e.currentStep||"Not recorded"}</td><td>{date(e.createdAt)}</td><td>{date(e.nextSendAt)}</td><td>{date(e.lastSentAt)}</td><td>{e.stopReason||"—"}</td><td><div className="flex gap-2">{canManage&&["Active","Paused"].includes(e.status)&&<button className={s.button} onClick={()=>{setTarget(e);setActionError("");}}>Remove from campaign</button>}{canDelete&&e.patientIds.length===1&&patients.has(e.patientIds[0])&&<DeletePatientButton id={e.patientIds[0]} name={name(e.patientIds)} onDeleted={refresh}/>}</div></td></tr>)}
      </tbody></table></div>}
      <footer className={s.footer}><span>Page {current} of {pages} · {SIZE} per page</span><div className="flex gap-2"><button className={s.button} disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><button className={s.button} disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div></footer>
    </section>}
    <PatientDialog open={Boolean(target)} onClose={()=>{if(!busy)setTarget(null);}} title="Remove from campaign?" eyebrow="Enrollment management" busy={busy} footer={<><button className={s.button} disabled={busy} onClick={()=>setTarget(null)}>Cancel</button><button className={s.button+" "+s.primary} disabled={busy} onClick={remove}>{busy?"Removing…":"Remove from campaign"}</button></>}>
      <p>{target?name(target.patientIds):""} will be marked Stopped with reason Manual. The next scheduled send will be cleared.</p><p className={s.muted}>The patient, enrollment and message history remain. Messages already sent to the delivery provider cannot be recalled.</p>{actionError&&<p role="alert" className={s.notice+" "+s.warning}>{actionError}</p>}
    </PatientDialog>
    <PatientDialog open={Boolean(message)} onClose={()=>setMessage(null)} title="Message details" eyebrow="Delivery history">{message&&<><dl className={s.detailGrid}>{[["Patient",name(message.patientIds)],["Channel",message.channel],["Sequence step",message.step||"Not recorded"],["Delivery status",message.status],["Sent at",date(message.sentAt)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className={s.messageBody}>{message.body||"Message body not recorded."}</div></>}</PatientDialog>
  </div>;
}
