"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import Link from "next/link";
import { ArrowLeft, MoreHorizontal, RefreshCw, Trash2, UserMinus, UserPlus, HeartHandshake, Mail, Search } from "lucide-react";
import { formatCampaignDate } from "@/lib/campaigns/campaign-date";
import type { ReactivationCampaignData } from "@/lib/reactivation/campaign";
import { EMAIL_STEPS, deliveryState, stepNumber, type Enrollment, type PatientMessage } from "@/lib/reactivation/model";
import PatientDialog from "./PatientDialog";
import { DeletePatientDialog } from "./DeletePatientButton";
import PatientDrawer, { MessageCard } from "./PatientDrawer";
import s from "./reactivation.module.css";
const date=(value:string)=>formatCampaignDate(value||null,"Not recorded");
const SIZE=10;
// Row actions in a small menu. Fixed positioning keeps it clear of the table's scroll area.
function RowMenu({label,children}:{label:string;children:(close:()=>void)=>ReactNode}){
  const [pos,setPos]=useState<{top?:number;bottom?:number;right?:number;left?:number;sheet?:boolean}|null>(null);
  const button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    if(!pos)return;
    const onPointer=(e:MouseEvent)=>{if(!menu.current?.contains(e.target as Node)&&!button.current?.contains(e.target as Node))setPos(null);};
    const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setPos(null);button.current?.focus();}};
    const close=()=>setPos(null);
    document.addEventListener("mousedown",onPointer);document.addEventListener("keydown",onKey);window.addEventListener("scroll",close,true);window.addEventListener("resize",close);
    menu.current?.querySelector<HTMLButtonElement>("button")?.focus();
    return()=>{document.removeEventListener("mousedown",onPointer);document.removeEventListener("keydown",onKey);window.removeEventListener("scroll",close,true);window.removeEventListener("resize",close);};
  },[pos]);
  return <><button ref={button} className={s.iconButton} aria-label={label} aria-haspopup="menu" aria-expanded={Boolean(pos)} onClick={e=>{e.stopPropagation();if(pos){setPos(null);return;}if(window.innerWidth<640){setPos({left:12,right:12,bottom:12,sheet:true});return;}const r=e.currentTarget.getBoundingClientRect();const right=window.innerWidth-r.right;setPos(window.innerHeight-r.bottom<140?{bottom:window.innerHeight-r.top+6,right}:{top:r.bottom+6,right});}}><MoreHorizontal size={17}/></button>
    {pos&&createPortal(<>{pos.sheet&&<div className={s.sheetBackdrop} aria-hidden="true"/>}<div ref={menu} role="menu" className={s.rowMenu+(pos.sheet?" "+s.rowMenuSheet:"")} style={{top:pos.top,bottom:pos.bottom,left:pos.left,right:pos.right}} onClick={e=>e.stopPropagation()}>{children(()=>setPos(null))}</div></>,document.body)}</>;
}
export default function ReactivationCampaign({initial,initialError,canManage,canDelete}:{initial:ReactivationCampaignData|null;initialError:string;canManage:boolean;canDelete:boolean}){
  const [data,setData]=useState(initial),[error,setError]=useState(initialError),[loading,setLoading]=useState(false);
  const [tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[status,setStatus]=useState("Current"),[channel,setChannel]=useState("All"),[page,setPage]=useState(1);
  const [patientId,setPatientId]=useState<string|null>(null),[openLog,setOpenLog]=useState<string|null>(null),[conversation,setConversation]=useState<string|null>(null),[deleting,setDeleting]=useState<{id:string;name:string}|null>(null);
  const [picked,setPicked]=useState<Set<string>>(new Set()),[bulkOpen,setBulkOpen]=useState(false);
  const [target,setTarget]=useState<Enrollment|null>(null),[message,setMessage]=useState<PatientMessage|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(""),[notice,setNotice]=useState("");
  async function refresh(){
    setLoading(true);setError("");
    try{const r=await fetch("/api/reactivation/campaign",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);}
    catch(e){setError(e instanceof Error?e.message:"Could not refresh campaign.");}finally{setLoading(false);}
  }
  async function remove(){
    const ids=target?[target.id]:[...picked];
    if(!ids.length||busy)return;setBusy(true);setActionError("");
    try{const r=await fetch("/api/reactivation/remove",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enrollmentIds:ids})});const b=await r.json();if(!r.ok)throw new Error(b.error);setTarget(null);setBulkOpen(false);setPicked(new Set());setNotice(b.removed.toLocaleString("en-US")+(b.removed===1?" patient":" patients")+" removed from the campaign. Enrollment records deleted; sent messages stay in history.");await refresh();}
    catch(e){setActionError(e instanceof Error?e.message:"Could not remove enrollment.");}finally{setBusy(false);}
  }
  if(!data)return <div className={s.empty}><HeartHandshake size={28}/><h3>Reactivation campaign unavailable</h3><p role="alert">{error}</p><button className={s.button} disabled={loading} onClick={refresh}><RefreshCw size={14} className={loading?"animate-spin":""}/>Retry</button></div>;
  const patients=new Map(data.patients.map(p=>[p.id,p]));
  const name=(ids:string[])=>ids.map(id=>patients.get(id)?.name||"Patient unavailable").join(", ")||"Patient deleted";
  const needle=query.trim().toLowerCase();
  const enrollments=data.enrollments.filter(e=>(status==="All"||(status==="Current"?["Active","Paused"].includes(e.status):e.status===status))&&[name(e.patientIds),e.currentStep,...e.patientIds.flatMap(id=>[patients.get(id)?.phone||"",patients.get(id)?.email||""])].join(" ").toLowerCase().includes(needle));
  const logs=data.messages.filter(m=>(status==="All"||status==="Current"||m.status===status)&&(channel==="All"||m.channel===channel)&&[name(m.patientIds),m.step,m.body].join(" ").toLowerCase().includes(needle));
  const conversations=[...logs.reduce((map,msg)=>{const key=msg.patientIds[0]||"message:"+msg.id;const list=map.get(key)||[];list.push(msg);return map.set(key,list);},new Map<string,PatientMessage[]>()).entries()].map(([key,items])=>({key,items,latest:items[0],enrollment:data.enrollments.find(e=>e.patientIds.includes(key))}));
  const rows=tab==="messages"?conversations:enrollments;
  const openConversation=conversations.find(c=>c.key===conversation)??null;
  const pages=Math.max(1,Math.ceil(rows.length/SIZE)),current=Math.min(page,pages);
  const m=data.metrics;
  function changeTab(next:string){setPicked(new Set());setTab(next);setOpenLog(null);setConversation(null);setQuery("");setStatus(next==="enrollments"?"Current":"All");setChannel("All");setPage(1);}
  const cardStatus=m.active?"Active":data.paused?"Paused":"Idle";
  return <div className={s.workspace}>
    <div className={s.campaignTop}><Link href="/campaigns" className={s.backLink}><ArrowLeft size={15}/>All campaigns</Link><div className="flex flex-wrap gap-2"><button className={s.button} disabled={loading} onClick={refresh}><RefreshCw size={14}/>{loading?"Refreshing…":"Refresh"}</button>{canManage&&<Link className={s.button+" "+s.primary} href="/dashboard/dormant-patients"><UserPlus size={15}/>Enroll patients</Link>}</div></div>
    <header className={s.campaignHero}><span className={s.avatar}><HeartHandshake size={23}/></span><div><span className={s.eyebrow}>Patient retention · Manual enrollment</span><h2>{data.campaign}</h2><p className={s.muted}>Bring patients back with a three-step email follow-up. Review who is enrolled, what is scheduled, and what was delivered.</p><p className={s.muted}>Last activity: {date(data.lastActivity)} · Updated {date(data.generatedAt)}</p></div><span className={s.badge+" "+(cardStatus==="Active"?"":s.neutral)}>{cardStatus}</span></header>
    {error&&<p className={s.notice+" "+s.warning} role="alert">{error} Showing the last loaded data.</p>}
    {notice&&<div className={s.notice} role="status">{notice}<button className="ml-4 underline" onClick={()=>setNotice("")}>Dismiss</button></div>}
    <div className={s.kpis}>{[["Enrolled",m.total,"Enrollment records"],["Active",m.active,data.paused+" paused"],["Emails sent",m.email,m.failures+" failed · "+m.pending+" pending"],["Booked patients",m.bookings,m.replies+" patients replied"]].map(([label,value,detail])=><article key={label} className={s.kpi}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div>
    <nav className={s.tabs} aria-label="Campaign sections">{[["overview","Overview"],["enrollments","Enrollments · "+data.enrollments.length],["messages","Conversations"]].map(([key,label])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>changeTab(key)}>{label}</button>)}</nav>
    {tab==="overview"?<>
      <div className={s.campaignGrid}><section className={s.panel}><div className={s.toolbar}><div><h3>Follow-up sequence</h3><p className={s.muted}>Current positions, based on active enrollments.</p></div></div><div className={s.sequence}>{EMAIL_STEPS.map((step,i)=>{const count=data.enrollments.filter(e=>e.status==="Active"&&stepNumber(e.currentStep)===i+1).length;return <article key={step}><span className={s.avatar}><Mail size={17}/></span><div><small>STEP {i+1}</small><h4>{step}</h4><p>{count} active {count===1?"patient":"patients"}</p></div></article>;})}</div><p className={s.footer}>Send timing and message content are controlled by the connected automation. This page reports saved schedules; it does not run the sender.</p>{EMAIL_STEPS.some(step=>data.messages.some(msg=>msg.step===step&&msg.body))&&<div className={s.emailPreviews}><h4>Emails as sent</h4>{EMAIL_STEPS.map(step=>{const sample=data.messages.find(msg=>msg.step===step&&msg.body);return sample?<button key={step} onClick={()=>setMessage(sample)}><strong>{step}</strong><span>{sample.body.split("\n").find(line=>line.trim()&&!/^hi/i.test(line.trim()))||sample.body}</span></button>:null;})}</div>}</section>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Enrollment outcomes</h3><p className={s.muted}>All-time enrollment status</p></div></div><div className={s.breakdown}>{[["Active",m.active],["Paused",data.paused],["Completed",m.completed],["Stopped",m.stopped]].map(([label,count])=><div key={label}><span>{label}</span><span className={s.progress}><i style={{width:(m.total?Number(count)/m.total*100:0)+"%"}}/></span><strong>{count}</strong></div>)}</div>{!m.total&&<p className={s.footer}>No enrollments yet. Add patients from the directory to begin.</p>}</section></div>
      <div className={s.campaignGrid}><section className={s.panel}><div className={s.toolbar}><div><h3>Upcoming sends</h3><p className={s.muted}>Earliest saved schedules · clinic timezone</p></div></div><div className={s.miniList}>{data.enrollments.filter(e=>e.status==="Active"&&e.nextSendAt).sort((a,b)=>Date.parse(a.nextSendAt)-Date.parse(b.nextSendAt)).slice(0,5).map(e=><div key={e.id}><strong>{name(e.patientIds)}</strong><span>{e.currentStep}</span><small>{date(e.nextSendAt)}</small></div>)}{!data.enrollments.some(e=>e.status==="Active"&&e.nextSendAt)&&<p className={s.muted}>No scheduled sends.</p>}</div></section>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Delivery & stop reasons</h3><p className={s.muted}>Recorded outcomes, not estimated performance</p></div></div><div className={s.miniList}><div><strong>{m.failures} failed · {m.pending} pending</strong><small>Failed covers rejected, invalid, bounced and spam reports. Queued and scheduled emails remain pending until a sent or delivery status is recorded. See the message log for each status.</small></div>{Object.entries(m.stopReasons).map(([reason,count])=><div key={reason}><span>{reason}</span><strong>{count}</strong></div>)}{!Object.keys(m.stopReasons).length&&<p className={s.muted}>No stop reasons recorded.</p>}</div></section></div>
      <section className={s.panel}><div className={s.toolbar}><div><h3>Recent messages</h3><p className={s.muted}>Latest delivery records linked to this campaign</p></div><button className={s.button} onClick={()=>changeTab("messages")}>View message log</button></div><div className={s.miniList}>{data.messages.slice(0,4).map(msg=><button key={msg.id} onClick={()=>setMessage(msg)}><strong>{name(msg.patientIds)}</strong><span>{msg.step||msg.channel} · {msg.status}</span><small>{date(msg.sentAt)}{msg.body?" · "+msg.body.replace(/\s+/g," ").slice(0,110)+(msg.body.length>110?"…":""):""}</small></button>)}{!data.messages.length&&<p className={s.muted}>No messages logged yet. Recorded email deliveries will appear here.</p>}</div></section>
    </>:<section className={s.panel}><div className={s.toolbar}><div><h3>{tab==="messages"?"Conversations":"Patient enrollments"}</h3><p className={s.muted}>{tab==="messages"?rows.length+(rows.length===1?" conversation":" conversations")+" · "+logs.length+(logs.length===1?" email":" emails"):rows.length+" matching records · newest first"}</p></div></div>
      <div className={s.filters}><label className={s.search}><Search size={16}/><input aria-label="Search campaign records" className={s.input} placeholder={tab==="messages"?"Search patient, step or message…":"Search patient, contact or step…"} value={query} onChange={e=>{setQuery(e.target.value);setPage(1);setPicked(new Set());}}/></label><label className={s.label}>Status<select className={s.input} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);setPicked(new Set());}}>{[...(tab==="messages"?["All"]:["Current","All"]),...new Set((tab==="messages"?data.messages:data.enrollments).map(r=>r.status))].map(v=><option key={v} value={v}>{v==="Current"?"Current (active & paused)":v}</option>)}</select></label>{tab==="messages"&&<label className={s.label}>Channel<select className={s.input} value={channel} onChange={e=>{setChannel(e.target.value);setPage(1);}}>{["All",...new Set(data.messages.map(m=>m.channel))].map(v=><option key={v}>{v}</option>)}</select></label>}</div>
      {!rows.length?<div className={s.empty}><Search size={24}/><h3>No {tab==="messages"?"messages":"enrollments"} match</h3><p className={s.muted}>Try another search or filter. No records are fabricated when activity is empty.</p></div>:tab==="messages"?<><div className={s.convStats}>{[["Conversations",conversations.length],["Emails",logs.length],["Sent",logs.filter(m=>deliveryState(m.status)==="sent").length],["Failed",logs.filter(m=>deliveryState(m.status)==="failed").length]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className={s.tableWrap}><table role="table" className={s.table+" "+s.campaignTable}><thead><tr>{["Patient","Contact","Campaign status","Sequence progress","Emails","Last sent","Delivery"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody role="rowgroup">{conversations.slice((current-1)*SIZE,current*SIZE).map(c=>{const contact=c.latest.patientIds.map(id=>patients.get(id)?.email||patients.get(id)?.phone).filter(Boolean).join(", ");return <tr role="row" key={c.key} onClick={()=>{setConversation(c.key);setOpenLog(null);}}><td role="cell" data-label="Patient"><button className={s.rowLink} onClick={e=>{e.stopPropagation();setConversation(c.key);setOpenLog(null);}}><strong>{name(c.latest.patientIds)}</strong></button></td><td role="cell" data-label="Contact">{contact||"—"}</td><td role="cell" data-label="Campaign status">{c.enrollment?<span className={s.badge+" "+(c.enrollment.status==="Active"?"":s.neutral)}>{c.enrollment.status}</span>:"—"}</td><td role="cell" data-label="Sequence progress">{c.enrollment?.currentStep||c.latest.step||"—"}</td><td role="cell" data-label="Emails"><strong>{c.items.length}</strong></td><td role="cell" data-label="Last sent">{date(c.latest.sentAt)}</td><td role="cell" data-label="Delivery"><span className={s.badge+" "+(deliveryState(c.latest.status)==="failed"?s.failedBadge:s.neutral)}>{c.latest.status}</span></td></tr>;})}</tbody></table></div></>:<>{canManage&&<div className={s.bulkBar}><label className={s.toggle}><input type="checkbox" checked={enrollments.length>0&&enrollments.every(e=>picked.has(e.id))} onChange={ev=>setPicked(ev.target.checked?new Set(enrollments.map(e=>e.id)):new Set())}/>Select all {enrollments.length.toLocaleString("en-US")} matching</label><span className={s.muted}>{picked.size.toLocaleString("en-US")} selected</span><button className={s.button+" "+s.dangerButton} disabled={!picked.size||busy} onClick={()=>{setTarget(null);setActionError("");setBulkOpen(true);}}><Trash2 size={14}/>Remove selected</button></div>}<div className={s.tableWrap}><table role="table" className={s.table+" "+s.campaignTable}><thead><tr>{["Patient","Status","Current step","Enrolled","Next send","Last sent","Stop reason","Actions"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody role="rowgroup">
      {enrollments.slice((current-1)*SIZE,current*SIZE).map(e=>{const pid=e.patientIds.length===1&&patients.has(e.patientIds[0])?e.patientIds[0]:null;const removable=canManage;return <tr role="row" key={e.id} onClick={()=>pid&&setPatientId(pid)}><td role="cell" data-label="Patient"><div className={s.pickCell}>{canManage&&<input type="checkbox" aria-label={"Select "+name(e.patientIds)} checked={picked.has(e.id)} onClick={ev=>ev.stopPropagation()} onChange={()=>setPicked(old=>{const next=new Set(old);if(next.has(e.id))next.delete(e.id);else next.add(e.id);return next;})}/>}<div>{pid?<button className={s.rowLink} onClick={ev=>{ev.stopPropagation();setPatientId(pid);}}><strong>{name(e.patientIds)}</strong></button>:<strong>{name(e.patientIds)}</strong>}<br/><small>{e.patientIds.map(id=>patients.get(id)?.email||patients.get(id)?.phone).filter(Boolean).join(", ")}</small></div></div></td><td role="cell" data-label="Status"><span className={s.badge+" "+(e.status==="Active"?"":s.neutral)}>{e.status}</span></td><td role="cell" data-label="Current step">{e.currentStep||"Not recorded"}</td><td role="cell" data-label="Enrolled">{date(e.createdAt)}</td><td role="cell" data-label="Next send">{date(e.nextSendAt)}</td><td role="cell" data-label="Last sent">{date(e.lastSentAt)}</td><td role="cell" data-label="Stop reason">{e.stopReason||"—"}</td><td role="cell" data-label="Actions" onClick={ev=>ev.stopPropagation()}>{(removable||(canDelete&&pid))?<RowMenu label={"Actions for "+name(e.patientIds)}>{close=><>{removable&&<button role="menuitem" onClick={()=>{close();setTarget(e);setActionError("");}}><UserMinus size={15}/>Remove from campaign</button>}{canDelete&&pid&&<button role="menuitem" className={s.menuDanger} onClick={()=>{close();setDeleting({id:pid,name:name(e.patientIds)});}}><Trash2 size={15}/>Delete patient</button>}</>}</RowMenu>:<span className={s.muted}>—</span>}</td></tr>;})}
      </tbody></table></div></>}
      <footer className={s.footer}><span>Page {current} of {pages} · {SIZE} per page</span><div className="flex gap-2"><button className={s.button} disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><button className={s.button} disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></div></footer>
    </section>}
    <PatientDialog open={Boolean(target)||bulkOpen} onClose={()=>{if(!busy){setTarget(null);setBulkOpen(false);}}} title={target||picked.size===1?"Remove from campaign?":"Remove "+picked.size.toLocaleString("en-US")+" patients from the campaign?"} eyebrow="Enrollment management" busy={busy} footer={<><button className={s.button} disabled={busy} onClick={()=>{setTarget(null);setBulkOpen(false);}}>Cancel</button><button className={s.button+" "+s.dangerButton} disabled={busy} onClick={remove}>{busy?"Removing…":"Remove from campaign"}</button></>}>
      <p>{target?name(target.patientIds):picked.size.toLocaleString("en-US")+(picked.size===1?" patient":" patients")} will be removed from the campaign. Their enrollment {target||picked.size===1?"record is":"records are"} deleted from Airtable and no more emails will be sent.</p><p className={s.muted}>Patients stay in the directory and can be enrolled again. Messages already sent stay in their history and can’t be recalled.</p>{bulkOpen&&picked.size>200&&<p className={s.muted}>Large removals take up to a minute. Keep this window open.</p>}{actionError&&<p role="alert" className={s.notice+" "+s.warning}>{actionError}</p>}
    </PatientDialog>
    <PatientDialog open={Boolean(openConversation)} onClose={()=>{setConversation(null);setOpenLog(null);}} title={openConversation?name(openConversation.latest.patientIds):"Conversation"} eyebrow="Communication" drawer>{openConversation&&<><p className={s.muted}>{openConversation.latest.patientIds.map(id=>patients.get(id)?.email).filter(Boolean).join(", ")||"No email on record"} · {openConversation.items.length} {openConversation.items.length===1?"email":"emails"}</p><div className="grid gap-3">{openConversation.items.map(msg=><MessageCard key={msg.id} message={msg} open={openLog===msg.id} onToggle={()=>setOpenLog(c=>c===msg.id?null:msg.id)}/>)}</div></>}</PatientDialog>
    <PatientDialog open={Boolean(message)} onClose={()=>setMessage(null)} title="Message details" eyebrow="Delivery history">{message&&<><dl className={s.detailGrid}>{[["Patient",name(message.patientIds)],["Channel",message.channel],["Sequence step",message.step||"Not recorded"],["Delivery status",message.status],["Sent at",date(message.sentAt)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className={s.messageBody}>{message.body||"Message body not recorded."}</div></>}</PatientDialog>
    <PatientDrawer patientId={patientId} onClose={()=>setPatientId(null)} canManage={canManage} canDelete={canDelete} onChanged={async(msg)=>{setNotice(msg);await refresh();}}/>
    {deleting&&<DeletePatientDialog id={deleting.id} name={deleting.name} open onClose={()=>setDeleting(null)} onDeleted={async()=>{setDeleting(null);setNotice("Patient and reactivation history permanently deleted.");await refresh();}}/>}
  </div>;
}
