"use client";
import { AlertTriangle, X } from "lucide-react";
import { useEffect, useRef } from "react";

type Props = { open:boolean; title:string; description:string; confirmLabel:string; cancelLabel?:string; destructive?:boolean; loading?:boolean; children?:React.ReactNode; onConfirm:()=>void; onCancel:()=>void };
export function ConfirmDialog({open,title,description,confirmLabel,cancelLabel="Cancel",destructive=false,loading=false,children,onConfirm,onCancel}:Props){
 const panel=useRef<HTMLDivElement>(null),cancel=useRef<HTMLButtonElement>(null),trigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(!open)return;trigger.current=document.activeElement as HTMLElement;cancel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!loading)onCancel();if(event.key==="Tab"&&panel.current){const focusable=[...panel.current.querySelectorAll<HTMLElement>('button:not([disabled]),[href],input:not([disabled]),select:not([disabled])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);trigger.current?.focus()}},[open,loading,onCancel]);
 if(!open)return null;return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/75 p-0 sm:items-center sm:p-4" onMouseDown={event=>{if(event.target===event.currentTarget&&!loading)onCancel()}}><div ref={panel} role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description" className="w-full max-w-lg rounded-t-2xl border p-5 shadow-2xl sm:rounded-2xl" style={{backgroundColor:"#111117",borderColor:destructive?"rgba(248,113,113,.32)":"rgba(201,168,76,.26)"}}><div className="flex items-start gap-3"><div className="rounded-xl p-2" style={{color:destructive?"#F87171":"#C9A84C",backgroundColor:destructive?"rgba(248,113,113,.1)":"rgba(201,168,76,.1)"}}><AlertTriangle size={18}/></div><div className="min-w-0 flex-1"><h2 id="confirm-title" className="text-lg font-bold text-[#F0ECE4]">{title}</h2><p id="confirm-description" className="mt-2 text-sm leading-6 text-[#9292A0]">{description}</p></div><button aria-label="Close" disabled={loading} onClick={onCancel} className="text-[#7A7A8A]"><X size={18}/></button></div>{children&&<div className="mt-4 rounded-xl border border-white/5 bg-black/20 p-4 text-sm text-[#B8B8C2]">{children}</div>}<div className="mt-5 flex justify-end gap-2"><button ref={cancel} disabled={loading} onClick={onCancel} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-[#A0A0AC]">{cancelLabel}</button><button disabled={loading} onClick={onConfirm} className="rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-50" style={{backgroundColor:destructive?"#C9555D":"#C9A84C",color:destructive?"white":"#08080C"}}>{loading?"Working…":confirmLabel}</button></div></div></div>
}
export function DestructiveConfirmDialog(props:Omit<Props,"destructive">){return <ConfirmDialog {...props} destructive/>}
export const BulkActionConfirmDialog=ConfirmDialog;
